task:
  name: Linux cache
  container:
    image: ubuntu:latest
  test_cache:
    folder: cache
    populate_script:
      - mkdir cache
      - >
        for i in {1..500}; do
          dd if=/dev/urandom of=cache/$RANDOM bs=1024 count=1024
        done
